### ISSUE TITLE
Licence file is omitted

### ISSUE THREAD

**Issue by IgorKarymov** [silviucpp/graylog_lager#1]
Hello. Could you please clarify and commit licence file for that project?
Something like apache2 will be perfect :)
Thanks.

**Comment by IgorKarymov** [comment]
@silviucpp Hello, again. Any chances for this?
I like your library very much, and i will prefer use it instead of ESL version (mainly because of chunking support), but I can't because my company politics very serious
about code licenses.
So I probably will have to write  "yet another graylog library" for erlang, if you will
not be able to help with this issue.

**Comment by silviucpp** [comment]
Hello,

Sorry ! I never seen this issue for some reason .. to many notifications. 
License will be MIT
